[
   {
      "alumno":"Adrian",
      "nota":9.89,
      "ranking":5
   },
   {
      "alumno":"Tulia",
      "nota":9,
      "ranking":150
   },
   {
      "alumno":"Eduardo",
      "nota":8.09,
      "ranking":50
   },
   {
      "alumno":"Samantha",
      "nota":7.09,
      "ranking":10
   },
   {
      "alumno":"Juliana",
      "nota":6.09,
      "ranking":210
   },
   {
      "alumno":"Juan",
      "nota":7.09,
      "ranking":250
   },
   {
      "alumno":"Valeria",
      "nota":4.09,
      "ranking":310
   },
   {
      "alumno":"Milena",
      "nota":3.09,
      "ranking":350
   },
   {
      "alumno":"Jorge",
      "nota":2.09,
      "ranking":410
   }
]
